# Generated by Django 4.2.1 on 2023-05-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_vehicleimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
